Catkin-ProjectName: roscpp_core
Version: 0.2.0
Description: Willow Garage low level build system macros and infrastructure
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard, Ken Conley
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake

Depends: genmsg,
         libboost-thread-dev,
         libboost-date-time-dev

Release-Pull: git://github.com/wg-debs/roscpp_core.git
Release-Push: git@github.com:wg-debs/roscpp_core.git

