Package: roscpp-core
Version: 0.1.0
Section: misc
Priority: extra
Architecture: any
Depends: python-empy, cmake, 
         @(PackagePrefix)genmsg, @(PackagePrefix)genpy, @(PackagePrefix)gencpp,
         libboost-thread-dev, libboost-date-time-dev
Build-Depends: cmake, python, python-empy, python-setuptools, 
               @(PackagePrefix)catkin, @(PackagePrefix)genmsg, 
               @(PackagePrefix)genpy, @(PackagePrefix)gencpp,
               libboost-thread-dev, libboost-date-time-dev
Description: Willow Garage low level build system macros and infrastructure
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard, Ken Conley
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Catkin-ProjectName: roscpp_core
Catkin-CopyrightType:  willowgarage
Catkin-Depends: catkin, genmsg
Catkin-DebRulesType: cmake
