Catkin-ProjectName: roscpp_core
Version: 0.2.1
Description: Underlying data libraries for roscpp messages.
Author: Josh Faust <jfaust@willowgarage.com>
Maintainer: Dirk Thomas <dthomas@willowgarage.com>
Homepage: http://www.ros.org/wiki/roscpp_core

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake

Depends: boost,
         genmsg

